/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author N9N0C
 */
public class menu extends javax.swing.JFrame {

    private String totalHarga = "Total Harga: Rp.0"; // Inisialisasi dengan nilai awal 0
    private String rincianPesanan;

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        jLabel_fullname.setText(register.name + "");
    }
    public static String jumlah;
     public void setJumlah(String a){
     jumlah = a;
     }
     
     public String getJumlah(){
     return this.jumlah;
     }
     
     public static String x;
     public void setx(String a){
     x = a;
     }
     
     public String getx(){
     return this.x;
     }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_fullname = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbxnasi = new javax.swing.JCheckBox();
        cbxnasicampur = new javax.swing.JCheckBox();
        cbxnasitelur = new javax.swing.JCheckBox();
        cbxnasiayam = new javax.swing.JCheckBox();
        cbxnasiikan = new javax.swing.JCheckBox();
        cbxtempegrg = new javax.swing.JCheckBox();
        cbxtatembacem = new javax.swing.JCheckBox();
        cbxtahubakso = new javax.swing.JCheckBox();
        cbxayamgprk = new javax.swing.JCheckBox();
        cbxayamlava = new javax.swing.JCheckBox();
        cbxayam = new javax.swing.JCheckBox();
        cbxikan = new javax.swing.JCheckBox();
        cbxsayuran = new javax.swing.JCheckBox();
        cbxorekterong = new javax.swing.JCheckBox();
        cbxbasobiasa = new javax.swing.JCheckBox();
        cbxmiebaso = new javax.swing.JCheckBox();
        cbxbasoberanak = new javax.swing.JCheckBox();
        cbxmieayam = new javax.swing.JCheckBox();
        cbxmieabakso = new javax.swing.JCheckBox();
        cbxmieaceker = new javax.swing.JCheckBox();
        cbxrotibakar = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        cbxchickenkatsu = new javax.swing.JCheckBox();
        jLabel26 = new javax.swing.JLabel();
        txfjumlah1 = new javax.swing.JTextField();
        txfjumlah2 = new javax.swing.JTextField();
        txfjumlah3 = new javax.swing.JTextField();
        txfjumlah4 = new javax.swing.JTextField();
        txfjumlah5 = new javax.swing.JTextField();
        txfjumlah6 = new javax.swing.JTextField();
        txfjumlah7 = new javax.swing.JTextField();
        txfjumlah8 = new javax.swing.JTextField();
        txfjumlah9 = new javax.swing.JTextField();
        txfjumlah10 = new javax.swing.JTextField();
        txfjumlah11 = new javax.swing.JTextField();
        txfjumlah12 = new javax.swing.JTextField();
        txfjumlah13 = new javax.swing.JTextField();
        txfjumlah14 = new javax.swing.JTextField();
        txfjumlah15 = new javax.swing.JTextField();
        txfjumlah16 = new javax.swing.JTextField();
        txfjumlah17 = new javax.swing.JTextField();
        txfjumlah18 = new javax.swing.JTextField();
        txfjumlah19 = new javax.swing.JTextField();
        txfjumlah20 = new javax.swing.JTextField();
        txfjumlah21 = new javax.swing.JTextField();
        txfjumlah22 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        cbxesteh = new javax.swing.JCheckBox();
        cbxgreentea = new javax.swing.JCheckBox();
        cbxthaitea = new javax.swing.JCheckBox();
        cbxesdawet = new javax.swing.JCheckBox();
        cbxpopice = new javax.swing.JCheckBox();
        cbxjusjeruk = new javax.swing.JCheckBox();
        cbxjustomat = new javax.swing.JCheckBox();
        cbxjuswortel = new javax.swing.JCheckBox();
        cbxjusalpukat = new javax.swing.JCheckBox();
        cbxjusnaga = new javax.swing.JCheckBox();
        cbxjussirsak = new javax.swing.JCheckBox();
        cbxjusjambu = new javax.swing.JCheckBox();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txfjumlah23 = new javax.swing.JTextField();
        txfjumlah24 = new javax.swing.JTextField();
        txfjumlah25 = new javax.swing.JTextField();
        txfjumlah26 = new javax.swing.JTextField();
        txfjumlah27 = new javax.swing.JTextField();
        txfjumlah28 = new javax.swing.JTextField();
        txfjumlah29 = new javax.swing.JTextField();
        txfjumlah30 = new javax.swing.JTextField();
        txfjumlah31 = new javax.swing.JTextField();
        txfjumlah32 = new javax.swing.JTextField();
        txfjumlah33 = new javax.swing.JTextField();
        txfjumlah34 = new javax.swing.JTextField();
        jButton_order = new javax.swing.JButton();
        jButton_logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel_fullname.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_fullname, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_fullname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setText("MAKANAN");

        jLabel2.setForeground(new java.awt.Color(204, 255, 204));
        jLabel2.setText("MENU");

        jLabel3.setForeground(new java.awt.Color(204, 255, 204));
        jLabel3.setText("HARGA");

        jLabel4.setForeground(new java.awt.Color(204, 255, 204));
        jLabel4.setText("JUMLAH");

        cbxnasi.setForeground(new java.awt.Color(204, 255, 204));
        cbxnasi.setText("Nasi");

        cbxnasicampur.setForeground(new java.awt.Color(204, 255, 204));
        cbxnasicampur.setText("Nasi Campur");

        cbxnasitelur.setForeground(new java.awt.Color(204, 255, 204));
        cbxnasitelur.setText("Nasi Telur");

        cbxnasiayam.setForeground(new java.awt.Color(204, 255, 204));
        cbxnasiayam.setText("Nasi Ayam");

        cbxnasiikan.setForeground(new java.awt.Color(204, 255, 204));
        cbxnasiikan.setText("Nasi Ikan");

        cbxtempegrg.setForeground(new java.awt.Color(204, 255, 204));
        cbxtempegrg.setText("Tempe Goreng");

        cbxtatembacem.setForeground(new java.awt.Color(204, 255, 204));
        cbxtatembacem.setText("Tahu Tempe Bacem");

        cbxtahubakso.setForeground(new java.awt.Color(204, 255, 204));
        cbxtahubakso.setText("Tahu Bakso");

        cbxayamgprk.setForeground(new java.awt.Color(204, 255, 204));
        cbxayamgprk.setText("Ayam Geprek");

        cbxayamlava.setForeground(new java.awt.Color(204, 255, 204));
        cbxayamlava.setText("Ayam Hot Lava");

        cbxayam.setForeground(new java.awt.Color(204, 255, 204));
        cbxayam.setText("Ayam");

        cbxikan.setForeground(new java.awt.Color(204, 255, 204));
        cbxikan.setText("Ikan");

        cbxsayuran.setForeground(new java.awt.Color(204, 255, 204));
        cbxsayuran.setText("Sayuran");

        cbxorekterong.setForeground(new java.awt.Color(204, 255, 204));
        cbxorekterong.setText("Orek / terong");

        cbxbasobiasa.setForeground(new java.awt.Color(204, 255, 204));
        cbxbasobiasa.setText("Bakso Biasa");

        cbxmiebaso.setForeground(new java.awt.Color(204, 255, 204));
        cbxmiebaso.setText("Mie Bakso");

        cbxbasoberanak.setForeground(new java.awt.Color(204, 255, 204));
        cbxbasoberanak.setText("Bakso Beranak");

        cbxmieayam.setForeground(new java.awt.Color(204, 255, 204));
        cbxmieayam.setText("Mie Ayam");

        cbxmieabakso.setForeground(new java.awt.Color(204, 255, 204));
        cbxmieabakso.setText("Mie Ayam Bakso");

        cbxmieaceker.setForeground(new java.awt.Color(204, 255, 204));
        cbxmieaceker.setText("Mie Ayam Ceker");

        cbxrotibakar.setForeground(new java.awt.Color(204, 255, 204));
        cbxrotibakar.setText("Roti Bakar");

        jLabel5.setForeground(new java.awt.Color(204, 255, 204));
        jLabel5.setText("Rp. 5.000");

        jLabel6.setForeground(new java.awt.Color(204, 255, 204));
        jLabel6.setText("Rp. 8.000");

        jLabel7.setForeground(new java.awt.Color(204, 255, 204));
        jLabel7.setText("Rp. 8.000");

        jLabel8.setForeground(new java.awt.Color(204, 255, 204));
        jLabel8.setText("Rp. 12.000");

        jLabel9.setForeground(new java.awt.Color(204, 255, 204));
        jLabel9.setText("Rp. 11.000");

        jLabel10.setForeground(new java.awt.Color(204, 255, 204));
        jLabel10.setText("Rp. 1.000");

        jLabel11.setForeground(new java.awt.Color(204, 255, 204));
        jLabel11.setText("Rp. 1.500");

        jLabel12.setForeground(new java.awt.Color(204, 255, 204));
        jLabel12.setText("Rp. 2.000");

        jLabel13.setForeground(new java.awt.Color(204, 255, 204));
        jLabel13.setText("Rp. 8.000");

        jLabel14.setForeground(new java.awt.Color(204, 255, 204));
        jLabel14.setText("Rp. 8.000");

        jLabel15.setForeground(new java.awt.Color(204, 255, 204));
        jLabel15.setText("Rp. 7.000");

        jLabel16.setForeground(new java.awt.Color(204, 255, 204));
        jLabel16.setText("Rp. 6.000");

        jLabel17.setForeground(new java.awt.Color(204, 255, 204));
        jLabel17.setText("Rp. 2.500");

        jLabel18.setForeground(new java.awt.Color(204, 255, 204));
        jLabel18.setText("Rp. 3.500");

        jLabel19.setForeground(new java.awt.Color(204, 255, 204));
        jLabel19.setText("Rp. 9.000");

        jLabel20.setForeground(new java.awt.Color(204, 255, 204));
        jLabel20.setText("Rp. 11.000");

        jLabel21.setForeground(new java.awt.Color(204, 255, 204));
        jLabel21.setText("Rp. 15.000");

        jLabel22.setForeground(new java.awt.Color(204, 255, 204));
        jLabel22.setText("Rp. 10.000");

        jLabel23.setForeground(new java.awt.Color(204, 255, 204));
        jLabel23.setText("Rp. 12.000");

        jLabel24.setForeground(new java.awt.Color(204, 255, 204));
        jLabel24.setText("Rp. 13.000");

        jLabel25.setForeground(new java.awt.Color(204, 255, 204));
        jLabel25.setText("Rp. 5.000");

        cbxchickenkatsu.setForeground(new java.awt.Color(204, 255, 204));
        cbxchickenkatsu.setText("Chicken Katsu");

        jLabel26.setForeground(new java.awt.Color(204, 255, 204));
        jLabel26.setText("Rp. 10.000");

        jLabel27.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 255, 204));
        jLabel27.setText("MINUMAN");

        jLabel28.setForeground(new java.awt.Color(204, 255, 204));
        jLabel28.setText("MENU");

        jLabel29.setForeground(new java.awt.Color(204, 255, 204));
        jLabel29.setText("HARGA");

        jLabel30.setForeground(new java.awt.Color(204, 255, 204));
        jLabel30.setText("JUMLAH");

        cbxesteh.setForeground(new java.awt.Color(204, 255, 204));
        cbxesteh.setText("Es Teh");

        cbxgreentea.setForeground(new java.awt.Color(204, 255, 204));
        cbxgreentea.setText("Green Tea");

        cbxthaitea.setForeground(new java.awt.Color(204, 255, 204));
        cbxthaitea.setText("Thai Tea");

        cbxesdawet.setForeground(new java.awt.Color(204, 255, 204));
        cbxesdawet.setText("Es Dawet");

        cbxpopice.setForeground(new java.awt.Color(204, 255, 204));
        cbxpopice.setText("Pop Ice");

        cbxjusjeruk.setForeground(new java.awt.Color(204, 255, 204));
        cbxjusjeruk.setText("Jus Jeruk");

        cbxjustomat.setForeground(new java.awt.Color(204, 255, 204));
        cbxjustomat.setText("Jus Tomat");

        cbxjuswortel.setForeground(new java.awt.Color(204, 255, 204));
        cbxjuswortel.setText("Jus Wortel");

        cbxjusalpukat.setForeground(new java.awt.Color(204, 255, 204));
        cbxjusalpukat.setText("Jus Alpukat");

        cbxjusnaga.setForeground(new java.awt.Color(204, 255, 204));
        cbxjusnaga.setText("Jus Naga");

        cbxjussirsak.setForeground(new java.awt.Color(204, 255, 204));
        cbxjussirsak.setText("Jus Sirsak");

        cbxjusjambu.setForeground(new java.awt.Color(204, 255, 204));
        cbxjusjambu.setText("Jus Jambu");

        jLabel31.setForeground(new java.awt.Color(204, 255, 204));
        jLabel31.setText("Rp. 2.000");

        jLabel32.setForeground(new java.awt.Color(204, 255, 204));
        jLabel32.setText("Rp. 5.000");

        jLabel33.setForeground(new java.awt.Color(204, 255, 204));
        jLabel33.setText("Rp. 5.000");

        jLabel34.setForeground(new java.awt.Color(204, 255, 204));
        jLabel34.setText("Rp. 5.000");

        jLabel35.setForeground(new java.awt.Color(204, 255, 204));
        jLabel35.setText("Rp. 3.000");

        jLabel36.setForeground(new java.awt.Color(204, 255, 204));
        jLabel36.setText("Rp. 7.000");

        jLabel37.setForeground(new java.awt.Color(204, 255, 204));
        jLabel37.setText("Rp. 6.000");

        jLabel38.setForeground(new java.awt.Color(204, 255, 204));
        jLabel38.setText("Rp. 6.000");

        jLabel39.setForeground(new java.awt.Color(204, 255, 204));
        jLabel39.setText("Rp. 8.000");

        jLabel40.setForeground(new java.awt.Color(204, 255, 204));
        jLabel40.setText("Rp. 8.000");

        jLabel41.setForeground(new java.awt.Color(204, 255, 204));
        jLabel41.setText("Rp. 9.000");

        jLabel42.setForeground(new java.awt.Color(204, 255, 204));
        jLabel42.setText("Rp. 9.000");

        jButton_order.setText("Pesan");
        jButton_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_orderActionPerformed(evt);
            }
        });

        jButton_logout.setFont(new java.awt.Font("Tw Cen MT", 1, 30)); // NOI18N
        jButton_logout.setText("X");
        jButton_logout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbxgreentea, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbxthaitea, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbxesdawet, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbxpopice, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbxjusjeruk, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbxjustomat, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbxjuswortel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbxjusalpukat, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbxjusnaga, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbxjussirsak, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbxjusjambu, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(148, 148, 148)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(48, 48, 48)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfjumlah23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfjumlah24, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfjumlah25, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfjumlah26, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfjumlah27, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfjumlah28, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfjumlah29, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfjumlah30, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfjumlah31, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfjumlah32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfjumlah33, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfjumlah34, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbxesteh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbxnasiikan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxtempegrg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxtatembacem, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(cbxtahubakso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxayamgprk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxayamlava, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxayam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxikan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxsayuran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxorekterong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxbasobiasa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxmiebaso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxbasoberanak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxmieayam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxmieabakso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxmieaceker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxrotibakar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxnasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxnasiayam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxnasicampur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxnasitelur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxchickenkatsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(148, 148, 148)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfjumlah1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txfjumlah3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(txfjumlah2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txfjumlah4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfjumlah5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfjumlah6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfjumlah7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfjumlah8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfjumlah9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfjumlah10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfjumlah11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfjumlah12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfjumlah13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfjumlah14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfjumlah15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfjumlah16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfjumlah17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfjumlah18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfjumlah19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfjumlah20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfjumlah21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfjumlah22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jButton_order, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfjumlah1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxnasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfjumlah2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxnasicampur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfjumlah3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxnasitelur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfjumlah4, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxnasiayam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfjumlah5, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxnasiikan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfjumlah6, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxtempegrg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfjumlah7, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxtatembacem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfjumlah8, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxtahubakso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfjumlah9, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxayamgprk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfjumlah10, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxayamlava, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfjumlah11, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxayam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfjumlah12, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxikan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfjumlah13, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxsayuran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfjumlah14, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxorekterong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfjumlah15, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxbasobiasa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfjumlah16, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxmiebaso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfjumlah17, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxbasoberanak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfjumlah18, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxmieayam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfjumlah19, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxmieabakso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfjumlah20, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxmieaceker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfjumlah21, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxrotibakar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txfjumlah22, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(cbxchickenkatsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfjumlah23, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxesteh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfjumlah24, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxgreentea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfjumlah25, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxthaitea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfjumlah26, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxesdawet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfjumlah27, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxpopice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfjumlah28, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxjusjeruk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfjumlah29, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxjustomat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfjumlah30, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxjuswortel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfjumlah31, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxjusalpukat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfjumlah32, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxjusnaga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfjumlah33, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxjussirsak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfjumlah34, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxjusjambu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton_order)
                .addGap(21, 21, 21))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_logoutActionPerformed
        // TODO add your handling code here:
        //go to logout
                logout lg = new logout();
            lg.setVisible(true);
            lg.pack();
            lg.setlocationRelativeTo(null);
            lg.setDefaultCloseOperation(register.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButton_logoutActionPerformed

    private void jButton_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_orderActionPerformed
        // TODO add your handling code here:
        // go to order
                
        // Inisialisasi variabel total bayar
    int totalHargaInt = 0;

    // String untuk menampilkan rincian pesanan
    StringBuilder tampil = new StringBuilder();

    // Menambahkan item-menu yang dipilih ke total bayar dan tampilan
        if (cbxnasi.isSelected()){
            int jumlah=Integer.parseInt(txfjumlah1.getText());
            int total;
            total=jumlah*5000;
            totalHargaInt += total;
            tampil.append(cbxnasi.getText()).append(" Rp.5.000 x ").append(jumlah).append(" = ").append(total).append("\n");
        }if (cbxnasicampur.isSelected()){
            int jumlah=Integer.parseInt(txfjumlah2.getText());
            int total;
            total=jumlah*8000;
            totalHargaInt += total;
            tampil.append(cbxnasicampur.getText()).append(" Rp.8.000 x ").append(jumlah).append(" = ").append(total).append("\n");
        }if (cbxnasitelur.isSelected()){
            int jumlah=Integer.parseInt(txfjumlah3.getText());
            int total;
            total=jumlah*8000;
            totalHargaInt += total;
            tampil.append(cbxnasitelur.getText()).append(" Rp.8.000 x ").append(jumlah).append(" = ").append(total).append("\n");
        }if (cbxnasiayam.isSelected()){
            int jumlah=Integer.parseInt(txfjumlah4.getText());
            int total;
            total=jumlah*12000;
            totalHargaInt += total;
            tampil.append(cbxnasiayam.getText()).append(" Rp.12.000 x ").append(jumlah).append(" = ").append(total).append("\n");
        }if (cbxnasiikan.isSelected()){
            int jumlah=Integer.parseInt(txfjumlah5.getText());
            int total;
            total=jumlah*11000;
            totalHargaInt += total;
            tampil.append(cbxnasiikan.getText()).append(" Rp.11.000 x ").append(jumlah).append(" = ").append(total).append("\n");
        }if (cbxtempegrg.isSelected()){
            int jumlah=Integer.parseInt(txfjumlah6.getText());
            int total;
            total=jumlah*1000;
            totalHargaInt += total;
            tampil.append(cbxtempegrg.getText()).append(" Rp.1.000 x ").append(jumlah).append(" = ").append(total).append("\n");
        }if (cbxtatembacem.isSelected()){
            int jumlah=Integer.parseInt(txfjumlah7.getText());
            int total;
            total=jumlah*1500;
            totalHargaInt += total;
            tampil.append(cbxtatembacem.getText()).append(" Rp.1.500 x ").append(jumlah).append(" = ").append(total).append("\n");
        }if (cbxtahubakso.isSelected()){
            int jumlah=Integer.parseInt(txfjumlah8.getText());
            int total;
            total=jumlah*2000;
            totalHargaInt += total;
            tampil.append(cbxtahubakso.getText()).append(" Rp.2.000 x ").append(jumlah).append(" = ").append(total).append("\n");
        }if (cbxayamgprk.isSelected()){
            int jumlah=Integer.parseInt(txfjumlah9.getText());
            int total;
            total=jumlah*8000;
            totalHargaInt += total;
            tampil.append(cbxayamgprk.getText()).append(" Rp.8.000 x ").append(jumlah).append(" = ").append(total).append("\n");
        }if (cbxayamlava.isSelected()){
            int jumlah=Integer.parseInt(txfjumlah10.getText());
            int total;
            total=jumlah*8000;
            totalHargaInt += total;
            tampil.append(cbxayamlava.getText()).append(" Rp.8.000 x ").append(jumlah).append(" = ").append(total).append("\n");
        }if (cbxayam.isSelected()){
            int jumlah=Integer.parseInt(txfjumlah11.getText());
            int total;
            total=jumlah*7000;
            totalHargaInt += total;
            tampil.append(cbxayam.getText()).append(" Rp.7.000 x ").append(jumlah).append(" = ").append(total).append("\n");
        }if (cbxikan.isSelected()){
            int jumlah=Integer.parseInt(txfjumlah12.getText());
            int total;
            total=jumlah*6000;
            totalHargaInt += total;
            tampil.append(cbxikan.getText()).append(" Rp.6.000 x ").append(jumlah).append(" = ").append(total).append("\n");
        }if (cbxsayuran.isSelected()){
            int jumlah=Integer.parseInt(txfjumlah13.getText());
            int total;
            total=jumlah*2500;
            totalHargaInt += total;
            tampil.append(cbxsayuran.getText()).append(" Rp.2.500 x ").append(jumlah).append(" = ").append(total).append("\n");
        }if (cbxorekterong.isSelected()){
            int jumlah=Integer.parseInt(txfjumlah14.getText());
            int total;
            total=jumlah*3500;
            totalHargaInt += total;
            tampil.append(cbxorekterong.getText()).append(" Rp.3.500 x ").append(jumlah).append(" = ").append(total).append("\n");
        }if (cbxbasobiasa.isSelected()){
            int jumlah=Integer.parseInt(txfjumlah15.getText());
            int total;
            total=jumlah*9000;
            totalHargaInt += total;
            tampil.append(cbxbasobiasa.getText()).append(" Rp.9.000 x ").append(jumlah).append(" = ").append(total).append("\n");
        }if (cbxmiebaso.isSelected()){
            int jumlah=Integer.parseInt(txfjumlah16.getText());
            int total;
            total=jumlah*11000;
            totalHargaInt += total;
            tampil.append(cbxmiebaso.getText()).append(" Rp.11.000 x ").append(jumlah).append(" = ").append(total).append("\n");
        }if (cbxbasoberanak.isSelected()){
            int jumlah=Integer.parseInt(txfjumlah17.getText());
            int total;
            total=jumlah*15000;
            totalHargaInt += total;
            tampil.append(cbxbasoberanak.getText()).append(" Rp.15.000 x ").append(jumlah).append(" = ").append(total).append("\n");
        }if (cbxmieayam.isSelected()){
            int jumlah=Integer.parseInt(txfjumlah18.getText());
            int total;
            total=jumlah*10000;
            totalHargaInt += total;
            tampil.append(cbxmieayam.getText()).append(" Rp.10.000 x ").append(jumlah).append(" = ").append(total).append("\n");
        }if (cbxmieabakso.isSelected()){
            int jumlah=Integer.parseInt(txfjumlah19.getText());
            int total;
            total=jumlah*12000;
            totalHargaInt += total;
            tampil.append(cbxmieabakso.getText()).append(" Rp.12.000 x ").append(jumlah).append(" = ").append(total).append("\n");
        }if (cbxmieaceker.isSelected()){
            int jumlah=Integer.parseInt(txfjumlah20.getText());
            int total;
            total=jumlah*13000;
            totalHargaInt += total;
            tampil.append(cbxmieaceker.getText()).append(" Rp.13.000 x ").append(jumlah).append(" = ").append(total).append("\n");
        }if (cbxrotibakar.isSelected()){
            int jumlah=Integer.parseInt(txfjumlah21.getText());
            int total;
            total=jumlah*5000;
            totalHargaInt += total;
            tampil.append(cbxrotibakar.getText()).append(" Rp.5.000 x ").append(jumlah).append(" = ").append(total).append("\n");
        }if (cbxchickenkatsu.isSelected()){
            int jumlah=Integer.parseInt(txfjumlah22.getText());
            int total;
            total=jumlah*10000;
            totalHargaInt += total;
            tampil.append(cbxchickenkatsu.getText()).append(" Rp.10.000 x ").append(jumlah).append(" = ").append(total).append("\n");
        }if (cbxesteh.isSelected()){
            int jumlah=Integer.parseInt(txfjumlah23.getText());
            int total;
            total=jumlah*2000;
            totalHargaInt += total;
            tampil.append(cbxesteh.getText()).append(" Rp.2.000 x ").append(jumlah).append(" = ").append(total).append("\n");
        }if (cbxgreentea.isSelected()){
            int jumlah=Integer.parseInt(txfjumlah24.getText());
            int total;
            total=jumlah*5000;
            totalHargaInt += total;
            tampil.append(cbxgreentea.getText()).append(" Rp.5.000 x ").append(jumlah).append(" = ").append(total).append("\n");
        }if (cbxthaitea.isSelected()){
            int jumlah=Integer.parseInt(txfjumlah25.getText());
            int total;
            total=jumlah*5000;
            totalHargaInt += total;
            tampil.append(cbxthaitea.getText()).append(" Rp.5.000 x ").append(jumlah).append(" = ").append(total).append("\n");
        }if (cbxesdawet.isSelected()){
            int jumlah=Integer.parseInt(txfjumlah26.getText());
            int total;
            total=jumlah*5000;
            totalHargaInt += total;
            tampil.append(cbxesdawet.getText()).append(" Rp.5.000 x ").append(jumlah).append(" = ").append(total).append("\n");
        }if (cbxpopice.isSelected()){
            int jumlah=Integer.parseInt(txfjumlah27.getText());
            int total;
            total=jumlah*3000;
            totalHargaInt += total;
            tampil.append(cbxpopice.getText()).append(" Rp.3.000 x ").append(jumlah).append(" = ").append(total).append("\n");
        }if (cbxjusjeruk.isSelected()){
            int jumlah=Integer.parseInt(txfjumlah28.getText());
            int total;
            total=jumlah*7000;
            totalHargaInt += total;
            tampil.append(cbxjusjeruk.getText()).append(" Rp.7.000 x ").append(jumlah).append(" = ").append(total).append("\n");
        }if (cbxjustomat.isSelected()){
            int jumlah=Integer.parseInt(txfjumlah29.getText());
            int total;
            total=jumlah*6000;
            totalHargaInt += total;
            tampil.append(cbxjustomat.getText()).append(" Rp.6.000 x ").append(jumlah).append(" = ").append(total).append("\n");
        }if (cbxjuswortel.isSelected()){
            int jumlah=Integer.parseInt(txfjumlah30.getText());
            int total;
            total=jumlah*6000;
            totalHargaInt += total;
            tampil.append(cbxjuswortel.getText()).append(" Rp.6.000 x ").append(jumlah).append(" = ").append(total).append("\n");
        }if (cbxjusalpukat.isSelected()){
            int jumlah=Integer.parseInt(txfjumlah31.getText());
            int total;
            total=jumlah*8000;
            totalHargaInt += total;
            tampil.append(cbxjusalpukat.getText()).append(" Rp.8.000 x ").append(jumlah).append(" = ").append(total).append("\n");
        }if (cbxjusnaga.isSelected()){
            int jumlah=Integer.parseInt(txfjumlah32.getText());
            int total;
            total=jumlah*8000;
            totalHargaInt += total;
            tampil.append(cbxjusnaga.getText()).append(" Rp.8.000 x ").append(jumlah).append(" = ").append(total).append("\n");
        }if (cbxjussirsak.isSelected()){
            int jumlah=Integer.parseInt(txfjumlah33.getText());
            int total;
            total=jumlah*9000;
            totalHargaInt += total;
            tampil.append(cbxjussirsak.getText()).append(" Rp.9.000 x ").append(jumlah).append(" = ").append(total).append("\n");
        }if (cbxjusjambu.isSelected()){
            int jumlah=Integer.parseInt(txfjumlah34.getText());
            int total;
            total=jumlah*9000;
            totalHargaInt += total;
            tampil.append(cbxjusjambu.getText()).append(" Rp.9.000 x ").append(jumlah).append(" = ").append(total).append("\n");
        }
        
        // Tambahkan biaya tambahan pengantaran dan penanganan (2000)
    totalHargaInt += 2000;
    tampil.append("Biaya Penanganan dan Pengantaran: Rp.2000\n");
    
         // Membuat objek frame order
    order orderFrame = new order();

    // Mengambil teks yang ada di dalam jTextArea_order sebelumnya
    String teksSebelumnya = orderFrame.getJTextArea_order().getText();

    // Menggabungkan teks yang sudah ada dengan tampil
    StringBuilder teksBaru = new StringBuilder(teksSebelumnya).append("\n").append(tampil);

    // Mengatur teks dalam jTextArea_order ke teksBaru
    orderFrame.getJTextArea_order().setText(teksBaru.toString());

    // Mengonversi totalHargaInt menjadi String dan menambahkannya ke totalHarga
    String totalHarga = "Total Harga: Rp." + totalHargaInt;

    // Menampilkan total harga di JTextArea pada frame order
    orderFrame.getJTextArea_order().append("\n" + totalHarga);

    // Menampilkan frame order
    orderFrame.setVisible(true);
    String b = String.valueOf(totalHarga);
     //Menampilkan Jframe cash
     String a = String.valueOf(totalHargaInt);
     setJumlah("Rp"+a);
     setx(teksBaru.toString());
    }//GEN-LAST:event_jButton_orderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbxayam;
    private javax.swing.JCheckBox cbxayamgprk;
    private javax.swing.JCheckBox cbxayamlava;
    private javax.swing.JCheckBox cbxbasoberanak;
    private javax.swing.JCheckBox cbxbasobiasa;
    private javax.swing.JCheckBox cbxchickenkatsu;
    private javax.swing.JCheckBox cbxesdawet;
    private javax.swing.JCheckBox cbxesteh;
    private javax.swing.JCheckBox cbxgreentea;
    private javax.swing.JCheckBox cbxikan;
    private javax.swing.JCheckBox cbxjusalpukat;
    private javax.swing.JCheckBox cbxjusjambu;
    private javax.swing.JCheckBox cbxjusjeruk;
    private javax.swing.JCheckBox cbxjusnaga;
    private javax.swing.JCheckBox cbxjussirsak;
    private javax.swing.JCheckBox cbxjustomat;
    private javax.swing.JCheckBox cbxjuswortel;
    private javax.swing.JCheckBox cbxmieabakso;
    private javax.swing.JCheckBox cbxmieaceker;
    private javax.swing.JCheckBox cbxmieayam;
    private javax.swing.JCheckBox cbxmiebaso;
    private javax.swing.JCheckBox cbxnasi;
    private javax.swing.JCheckBox cbxnasiayam;
    private javax.swing.JCheckBox cbxnasicampur;
    private javax.swing.JCheckBox cbxnasiikan;
    private javax.swing.JCheckBox cbxnasitelur;
    private javax.swing.JCheckBox cbxorekterong;
    private javax.swing.JCheckBox cbxpopice;
    private javax.swing.JCheckBox cbxrotibakar;
    private javax.swing.JCheckBox cbxsayuran;
    private javax.swing.JCheckBox cbxtahubakso;
    private javax.swing.JCheckBox cbxtatembacem;
    private javax.swing.JCheckBox cbxtempegrg;
    private javax.swing.JCheckBox cbxthaitea;
    private javax.swing.JButton jButton_logout;
    private javax.swing.JButton jButton_order;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_fullname;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txfjumlah1;
    private javax.swing.JTextField txfjumlah10;
    private javax.swing.JTextField txfjumlah11;
    private javax.swing.JTextField txfjumlah12;
    private javax.swing.JTextField txfjumlah13;
    private javax.swing.JTextField txfjumlah14;
    private javax.swing.JTextField txfjumlah15;
    private javax.swing.JTextField txfjumlah16;
    private javax.swing.JTextField txfjumlah17;
    private javax.swing.JTextField txfjumlah18;
    private javax.swing.JTextField txfjumlah19;
    private javax.swing.JTextField txfjumlah2;
    private javax.swing.JTextField txfjumlah20;
    private javax.swing.JTextField txfjumlah21;
    private javax.swing.JTextField txfjumlah22;
    private javax.swing.JTextField txfjumlah23;
    private javax.swing.JTextField txfjumlah24;
    private javax.swing.JTextField txfjumlah25;
    private javax.swing.JTextField txfjumlah26;
    private javax.swing.JTextField txfjumlah27;
    private javax.swing.JTextField txfjumlah28;
    private javax.swing.JTextField txfjumlah29;
    private javax.swing.JTextField txfjumlah3;
    private javax.swing.JTextField txfjumlah30;
    private javax.swing.JTextField txfjumlah31;
    private javax.swing.JTextField txfjumlah32;
    private javax.swing.JTextField txfjumlah33;
    private javax.swing.JTextField txfjumlah34;
    private javax.swing.JTextField txfjumlah4;
    private javax.swing.JTextField txfjumlah5;
    private javax.swing.JTextField txfjumlah6;
    private javax.swing.JTextField txfjumlah7;
    private javax.swing.JTextField txfjumlah8;
    private javax.swing.JTextField txfjumlah9;
    // End of variables declaration//GEN-END:variables
}
